version: '2'
services:
  web: #&app_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - db
    tty: true
    stdin_open: true
  # spring:
  #   <<: *app_base
  #   command: bundle exec spring server
  #   ports: []
  #   tty: false
  #   stdin_open: false
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=demo
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
    volumes:
        - ./mysql/init/:/docker-entrypoint-initdb.d
    volumes_from:
      - data
  data:
    image: busybox:latest
    volumes:
      - /var/lib/mysql
    tty: true