version: '3'
services:
  web:
    build: .
    command: bundle exec foreman start
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db_data:
